name: firebase_auth_tizen
description: Firebase Auth for Tizen
version: 0.1.0
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/firebase_auth_tizen

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  firebase_auth: ^3.6.2
  firebase_auth_dart: ^1.0.1
  firebase_auth_platform_interface: ^6.5.2
  firebase_core: ^1.20.0
  firebase_core_dart: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      tizen:
        dartPluginClass: FirebaseAuthDesktop
